### ISSUE TITLE
error with pinkies broxy

### ISSUE THREAD

**Issue by Owyn** [Binkyface/Event-Mob-Finder#1]
```
  ERROR tera-proxy-game: [dispatch] write: failed to generate S_SPAWN_DROPITEM<6>
error: [protocol] write - S_SPAWN_DROPITEM<6>: error writing "gameId" (type: uint64)
data: { low: 885394, high: 0, unsigned: true }
reason: Cannot mix BigInt and other types, use explicit conversions
    at Writeable.uint64 (\Tera-Proxy\node_modules\tera-data-parser\protocol\stream.js:133:24)
    at writeField (\Tera-Proxy\node_modules\tera-data-parser\protocol\index.js:510:20)
    at TeraProtocol.write (\Tera-Proxy\node_modules\tera-data-parser\protocol\index.js:525:4)
    at Dispatch.write (\Tera-Proxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:338:21)
    at DispatchWrapper.toClient (\Tera-Proxy\node_modules\tera-proxy-game\lib\connection\dispatch\dispatchWrapper.js:52:39)
    at Object.EventMobFinder.dispatch.hook.event [as callback] (\Tera-Proxy\bin\node_modules\Event-Mob-Finder-master\index.js:16:13)
```

**Comment by Sunpui** [comment]
should work now.
